// Generated by assemble.js — do not edit manually
import NavMinimal from "@/components/NavMinimal";
import HeroSplit from "@/components/HeroSplit";
import StatsRow from "@/components/StatsRow";
import AboutFounder from "@/components/AboutFounder";
import ServicesAlternating from "@/components/ServicesAlternating";
import ServicesIconGrid from "@/components/ServicesIconGrid";
import StatsFullBleed from "@/components/StatsFullBleed";
import ProcessSteps from "@/components/ProcessSteps";
import ContactSimple from "@/components/ContactSimple";
import FooterWordmark from "@/components/FooterWordmark";

export default function Home() {
  return (
    <>
      <NavMinimal
        brandName={"Peak Search Fund"}
        links={[{"label":"About","href":"#about"},{"label":"Criteria","href":"#criteria"},{"label":"Why Us","href":"#why"},{"label":"Process","href":"#process"},{"label":"Connect","href":"#contact"}]}
        ctaLabel={"Start a Conversation"}
        ctaHref={"#contact"}
      />
      <main>
      <HeroSplit
        eyebrow={"Search Fund · Richmond, Virginia"}
        headline={"Acquiring a great Virginia or North Carolina business —"}
        headlineAccent={"and running it."}
        body={"Peak Search Fund is the acquisition vehicle of Aidan O'Sullivan — a 20-year manufacturing and operations executive seeking to acquire and lead an exceptional business in Virginia or North Carolina."}
        ctaPrimary={"Start a Conversation"}
        ctaPrimaryHref={"#contact"}
        ctaSecondary={"View Criteria"}
        ctaSecondaryHref={"#criteria"}
        accentWord={"Acquire"}
      />
      <StatsRow
        stats={[{"value":"20+","label":"Years Operating Experience"},{"value":"$2.5M–$6M","label":"Target Acquisition Size"},{"value":"VA & NC","label":"Primary Geography"},{"value":"Day 1","label":"Active Principal Leadership"}]}
      />
      <AboutFounder
        eyebrow={"About the Buyer"}
        headline={"Aidan O'Sullivan"}
        headlineAccent={"Founder & Principal"}
        bioP1={"I spent two decades leading manufacturing and supply chain operations, most recently as President of Americas at an advanced manufacturing company. I know how to walk a shop floor, read a P&L, identify operational waste, and earn a team's trust. I'm not looking to acquire a business and disappear — I'm looking to be actively involved in leading and growing what comes next."}
        bioP2={"My background is in businesses that run on technical expertise, hands-on operations, and customer relationships that take years to earn. I bring the financial rigor and operational discipline of the large-company world — without the exit pressure, portfolio conflicts, or committee approvals."}
        credentials={[{"label":"Most Recent Role","value":"President, Americas — Advanced Manufacturing"},{"label":"MBA","value":"Finance & Strategy, Stern School of Business, NYU"},{"label":"Engineering","value":"B.Eng Mechanical Engineering, Trinity College Dublin"},{"label":"Background","value":"20+ Years Manufacturing & Supply Chain"},{"label":"Location","value":"Richmond, Virginia"}]}
        quote={"An operator, not a fund manager."}
      />
      <ServicesAlternating
        eyebrow={"Acquisition Criteria"}
        headline={"What Peak Search Fund"}
        headlineAccent={"is looking for."}
        items={[{"title":"Business Type","body":"Technically specialized industrial services, niche or specialty manufacturing, specialty fabrication, and B2B businesses with recurring revenue. These are the operating environments that match a background built on engineering, physical operations, and technically complex customer relationships.","tag":"Manufacturing · Industrial Services · Fabrication"},{"title":"Size & Financials","body":"Profitable businesses in the lower middle market with strong, demonstrable earnings and a clear financial history. Typical enterprise value in the $2.5M–$6M range. SBA-eligible structures preferred.","tag":"Recurring Revenue · SBA-Eligible"},{"title":"Geography","body":"Virginia and North Carolina, with a preference for businesses within reasonable proximity to Richmond — covering Hampton Roads, Northern Virginia, Charlottesville, Fredericksburg, Roanoke, Lynchburg, and the Research Triangle and Piedmont regions of North Carolina.","tag":"Virginia · North Carolina"},{"title":"Seller Situation","body":"Ownership considering a transition for any reason — retirement, succession, partnership changes, or simply the right time meeting the right buyer. Businesses that benefit from technically capable, committed leadership stepping in.","tag":"Retirement · Succession · Partnership Changes"},{"title":"Operations Profile","body":"Stable customer relationships, a capable workforce, and a defensible market position — possibly with operational upside that an experienced industrial operator can identify and unlock.","tag":"Recurring Revenue · Defensible Position"}]}
      />
      <ServicesIconGrid
        eyebrow={"Why Sell to Peak"}
        headline={"Your business in"}
        headlineAccent={"capable hands."}
        items={[{"icon":"bolt","title":"A Buyer Who Understands What You Built","body":"Peak Search Fund speaks manufacturing. Reading a routing sheet, understanding a work center, having real conversations with a technical team — without needing a six-month translation period."},{"icon":"star","title":"Committed, Not Transactional","body":"Fully committed to this acquisition — not distracted by competing deals, not managing a portfolio, not treating this as a stepping stone. The acquired company receives complete focus from day one."},{"icon":"check","title":"Certainty of Close","body":"Financing already structured with personal equity committed and a named SBA lender relationship in place. No financing contingencies, no LP sign-offs, no committee approvals."},{"icon":"shield","title":"Confidentiality, Always","body":"Every conversation is treated with the discretion it deserves. Employees, customers, and suppliers do not learn about a potential sale unless both sides decide they should — and only when both sides are ready."},{"icon":"chart","title":"Straightforward Deal Process","body":"Deal structure is determined by what the business and transaction facts support — not a predetermined template. The process is clean, discreet, and managed by a buyer with the operational and financial sophistication to get to close without drama."},{"icon":"people","title":"Supported by Experienced Advisors","body":"Legal, financial, and operational advisors with lower middle market transaction experience — ensuring a smooth, professional process for both sides of the transaction."}]}
      />
      <StatsFullBleed
        eyebrow={"Why Now"}
        headline={"The window"}
        headlineAccent={"is open."}
        body={"A generational wave of founder-owned and family-operated industrial businesses — built in the 1980s, 90s, and early 2000s — is approaching a natural ownership horizon. Owners who have a direct, confidential conversation with the right buyer now retain maximum control over the outcome, the timeline, and who ends up running what they built."}
        stats={[{"value":"~$10T","label":"Value of Boomer-owned businesses expected to transfer ownership this decade"},{"value":"70%","label":"Of small business owners with no formal succession plan in place"},{"value":"Off-Market","label":"The best transactions rarely start on a listing platform — they start with a direct conversation"}]}
      />
      <ProcessSteps
        eyebrow={"How It Works"}
        headline={"A straightforward"}
        headlineAccent={"process."}
        steps={[{"title":"Introductory Conversation","body":"A confidential, no-obligation call to understand the business, the seller's goals, and whether there is a genuine fit. No NDA required at this stage. (~30 minutes)"},{"title":"Initial Financial Review","body":"With an NDA in place, Peak Search Fund reviews three years of financials and a brief business overview to establish a working valuation range. (1–2 weeks)"},{"title":"Site Visit & Management Meeting","body":"An in-person visit to the facility, meeting the team, and understanding the operations directly. This is where real assessment happens — on the floor, not in a spreadsheet."},{"title":"Letter of Intent","body":"A clear, straightforward LOI delivered with a defined valuation range and proposed structure. No surprises, no games — just a serious, well-reasoned offer from a committed buyer."}]}
      />
      <ContactSimple
        eyebrow={"Connect"}
        headline={"Start a"}
        headlineAccent={"Conversation."}
        body={"Every inquiry is treated with complete confidentiality. There is no obligation, no NDA required for an initial call, and no pressure. If there is a fit, we will know quickly."}
        email={"aidan@peaksearchfund.com"}
        location={"Richmond, Virginia"}
      />
      </main>
      <FooterWordmark
        brandName={"Peak Search Fund"}
        tagline={"Acquiring great businesses. Running them well."}
        email={"aidan@peaksearchfund.com"}
        location={"Richmond, Virginia"}
      />
    </>
  );
}
